# Generated by Django 4.0.4 on 2022-05-25 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 25, 10, 24, 25, 225918)),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
