# Generated by Django 4.0.4 on 2022-06-01 10:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0009_alter_verificationcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 10, 30, 16, 440345, tzinfo=utc)),
        ),
    ]
