# Generated by Django 3.2.13 on 2022-06-01 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledledger',
            name='scheduled_date',
            field=models.DateField(default=datetime.date(2022, 6, 1)),
            preserve_default=False,
        ),
    ]
