# Generated by Django 4.0.4 on 2022-05-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=42241480, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
