# Generated by Django 4.0.4 on 2022-05-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_no',
            field=models.IntegerField(default=100001),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
