# Generated by Django 3.2.13 on 2022-06-03 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_scheduledledger_scheduled_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='credit_account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.account'),
            preserve_default=False,
        ),
    ]
