# Generated by Django 4.0.4 on 2022-05-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_account_account_no_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_no',
            field=models.IntegerField(unique=True),
        ),
    ]
