# Generated by Django 4.0.4 on 2022-05-19 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_bank_alter_account_balance_alter_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='bank_id',
            field=models.ForeignKey(default='DK-bankbuddy-1', on_delete=django.db.models.deletion.CASCADE, to='base.bank'),
            preserve_default=False,
        ),
    ]
