# Generated by Django 4.0.4 on 2022-05-20 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_ledger_bank_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='bank_id',
        ),
        migrations.AddField(
            model_name='ledger',
            name='bank',
            field=models.ForeignKey(blank=True, default='DK-bankbuddy-1', on_delete=django.db.models.deletion.CASCADE, to='base.bank'),
            preserve_default=False,
        ),
    ]
