# Generated by Django 4.0.4 on 2022-05-20 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_ledger_bank_id_ledger_bank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledger',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='customer',
            name='bank',
            field=models.ForeignKey(default='DK-bankbuddy-1', on_delete=django.db.models.deletion.CASCADE, to='base.bank'),
            preserve_default=False,
        ),
    ]
