# Generated by Django 4.0.4 on 2022-05-20 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_ledger_options_customer_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='bank',
        ),
    ]
