# Generated by Django 4.0.4 on 2022-05-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_account_balance_remove_ledger_from_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='customer',
            field=models.IntegerField(),
        ),
    ]
