# Generated by Django 4.0.4 on 2022-05-26 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_account_balance_remove_ledger_from_account_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ledger',
            new_name='AccountLedger',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='balance',
        ),
        migrations.AddField(
            model_name='loan',
            name='account_no',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.customer'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.customer'),
        ),
        migrations.AlterModelTable(
            name='accountledger',
            table='account_ledger',
        ),
        migrations.CreateModel(
            name='LoanLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Credit'), (2, 'Debit')])),
                ('message', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.loan')),
            ],
            options={
                'db_table': 'loan_ledger',
            },
        ),
    ]
