# Generated by Django 4.0.4 on 2022-05-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_ledger_account_alter_loan_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='account',
            field=models.CharField(max_length=50),
        ),
    ]
