# Generated by Django 4.0.4 on 2022-05-27 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_ledger_remove_loanledger_loan_delete_accountledger_and_more'),
        ('base', '0016_alter_ledger_account'),
    ]

    operations = [
    ]
